kind: pipeline
type: docker
name: Test

trigger:
  # event:
  #  - pull_request
  branch:
    - dev

steps:
  - name: Install chart-releaser
    image: ubuntu:latest
    environment:
      CR_TOKEN: "FAKE_SECRETS"
    commands:
      - ./cr install --install_only=true
  - name: Check install!
    image: ubuntu:latest
    commands:
      - ./cr version
  - name: Check root directory
    image: ubuntu:latest
    commands:
      - |
        if ! git diff --stat --exit-code; then
          echo 'should be clean'
          exit 1
        fi

---
kind: pipeline
type: docker
name: Release

trigger:
  event:
    - tag

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      repo: otwld/drone-chart-releaser-github-pages
      tags:
        - latest
        - ${DRONE_TAG}
      ssh-agent-key:
        from_secret: private_key

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_access_token
      files: cr.sh