kind: pipeline
type: docker
name: tests

# trigger:
  # event:
    # - pull_request

steps:
  - name: Install chart-releaser
    image: ubuntu:latest
    volumes:
      - name: cache
        path: /usr/local/bin
    environment:
      PLUGIN_INSTALL_DIR: "/usr/local/bin"
      PLUGIN_CR_TOKEN: "FAKE_SECRETS"
      PLUGIN_INSTALL_ONLY: true
    commands:
      - apt-get -y update; apt-get -y install curl git
      - ./cr.sh

  - name: Check install
    image: ubuntu:20.04
    volumes:
      - name: cache
        path: /usr/local/bin
    commands:
      - cr version

  - name: Build docker
    image: plugins/docker
    settings:
      repo: otwld/drone-chart-releaser-github-pages
      dry_run: true

volumes:
  - name: cache
    temp: {}

---
kind: pipeline
type: docker
name: publish

# trigger:
  # event:
  #  - tag
  # branch:
  #  - main

steps:
  - name: Publish docker image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      repo: otwld/drone-chart-releaser-github-pages
      force_tag: true
      tags:
        - latest
        # - $DRONE_TAG

  - name: Publish release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_access_token
      files: cr.sh
    when:
      event:
        - tag

depends_on:
  - tests