kind: pipeline
type: docker
name: Test

trigger:
  # event:
  #  - pull_request
  branch:
    - dev

steps:
  - name: Install chart-releaser
    image: ubuntu:latest
    volumes:
      - name: cache
        path: /cr
    environment:
      INSTALL_DIR: "/cr"
    commands:
      - ./cr.sh --install_only=true
  - name: Check install
    image: ubuntu:latest
    volumes:
      - name: cache
        path: /cr
    commands:
      - /cr version

volumes:
  - name: cache
    temp: {}

---

kind: pipeline
type: docker
name: Release

trigger:
  branch:
    - dev

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      repo: otwld/drone-chart-releaser-github-pages
      force_tag: true
      tags:
        - latest
       # - ${DRONE_TAG}

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_access_token
      files: cr.sh
    when:
      event:
        - tag