kind: pipeline
type: docker
name: tests

trigger:
  # event:
  #  - pull_request
  branch:
    - dev

steps:
  - name: Install chart-releaser
    image: ubuntu:latest
    volumes:
      - name: cache
        path: /tmp/bin
    environment:
      PLUGIN_INSTALL_DIR: "/tmp/bin"
      PLUGIN_CR_TOKEN: "FAKE_SECRETS"
    commands:
      - ls
      - ./cr.sh --install_only=true
      - ls -la /tmp/bin
    # event:
    #  - pull_request
    #  - tag

  - name: Check install
    image: ubuntu:latest
    volumes:
      - name: cache
        path: /tmp/bin
    commands:
      - ls -la /tmp/bin
      - /tmp/bin/cr version
    # event:
    #  - pull_request
    #  - tag

  - name: Build docker
    image: plugins/docker
    settings:
      repo: otwld/drone-chart-releaser-github-pages
      dry_run: true
    # when:
    #  event:
    #    - pull_request
    #    - tag

volumes:
  - name: cache
    temp: {}

---
kind: pipeline
type: docker
name: publish

trigger:
  # event:
  # - tag
  branch:
    - dev

steps:
  - name: Publish docker image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      repo: otwld/drone-chart-releaser-github-pages
      force_tag: true
      tags:
        - latest
        - ${DRONE_TAG}

  - name: Publish release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_access_token
      files: cr.sh

depends_on:
- tests