kind: pipeline
type: docker
name: Test

trigger:
  # event:
  #  - pull_request
  branch:
    - dev

steps:
  - name: Install chart-releaser
    image: ubuntu:latest
    volumes:
      - name: cache
        path: /cr
    environment:
      PLUGIN_INSTALL_DIR: "/cr"
      PLUGIN_CR_TOKEN: "FAKE_SECRETS"
    commands:
      - ./cr.sh --install_only=true
    # event:
    #  - pull_request
    #  - tag

  - name: Check install
    image: ubuntu:latest
    volumes:
      - name: cache
        path: /cr
    commands:
      - chmod +x /cr && /cr version
    # event:
    #  - pull_request
    #  - tag

  - name: Build docker
    image: plugins/docker
    settings:
      repo: otwld/drone-chart-releaser-github-pages
      dry_run: true
    # when:
    #  event:
    #    - pull_request
    #    - tag

  - name: Publish docker image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      repo: otwld/drone-chart-releaser-github-pages
      force_tag: true
      tags:
        - latest
        - ${DRONE_TAG}
    when:
      event:
        - tag

  - name: Publish release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_access_token
      files: cr.sh
    when:
      event:
        - tag

volumes:
  - name: cache
    temp: {}